[options]
addons_path = /home/anas/odoo_projects/odoo_test_project/odoo_test_project/addons,
	/home/anas/odoo_projects/odoo_test_project/odoo_test_project/odoo/addons,
	/home/anas/odoo_projects/odoo_test_project/odoo_test_project/odoo/custom_addons
db_host = 127.0.0.1
db_port = 5432
db_user = odoo17_testuser
db_password = testuser


